language: rust
matrix:
  include:
    - rust: stable
    - env: F=zlib-ng
      rust: stable
    - os: osx
    - env: F=zlib-ng
      os: osx

    - env: LIBZ_SYS_STATIC=1
    - env: LIBZ_SYS_STATIC=1
      os: osx

    - rust: stable
      script:
        - cargo generate-lockfile
        - ci/run-docker.sh

    - rust: beta
    - env: F=zlib-ng
      rust: beta

    - rust: nightly
    - env: F=zlib-ng
      rust: nightly
script:
  - cargo test ${F:+--no-default-features} ${F:+--features} $F
  - cargo run --manifest-path systest/Cargo.toml ${F:+--features} $F
notifications:
  email:
    on_success: never
